from __future__ import annotations

import argparse
from collections.abc import Iterable, Sequence
from pathlib import Path

import pandas as pd

from dataset_columns import (
    APP_DATA_LBJ_TRAIT_COLUMNS,
    ECOREGION_ID,
    RECOMMENDATION_CATEGORY,
    USAGE_KEY,
)
from etl.app_data import (
    DEFAULT_LBJ_TRAITS_PATHS,
    DEFAULT_PLANT_ECOREGIONS_PATH,
    DEFAULT_RECOMMENDATION_CATEGORIES_PATH,
    lbj_enrichment_mask,
    read_lbj_traits,
    read_recommendation_categories,
)
from etl.functions import normalize_key


def build_audit(
    plant_ecoregions: pd.DataFrame,
    lbj_traits: pd.DataFrame,
    categories: pd.DataFrame,
) -> dict:
    plants = plant_ecoregions.copy()
    plants[USAGE_KEY] = plants[USAGE_KEY].map(normalize_key)
    species = plants.drop_duplicates(USAGE_KEY)
    traits = lbj_traits.copy()
    traits[USAGE_KEY] = traits[USAGE_KEY].map(normalize_key)
    merged = species[[USAGE_KEY]].merge(traits, on=USAGE_KEY, how="left")
    merged = merged.merge(categories, on=USAGE_KEY, how="left")
    enriched = lbj_enrichment_mask(merged)
    trait_fields = [field for field in APP_DATA_LBJ_TRAIT_COLUMNS if field != USAGE_KEY and field in merged]
    completeness = {
        field: int(merged.loc[enriched, field].notna().sum())
        for field in trait_fields
    }
    populated = merged[trait_fields].notna().sum(axis=1) if trait_fields else pd.Series(0, index=merged.index)

    region_rows = plants[[USAGE_KEY, ECOREGION_ID]].merge(categories, on=USAGE_KEY, how="left")
    regional = (
        region_rows.assign(category=region_rows[RECOMMENDATION_CATEGORY].fillna("unlabeled_enriched"))
        .groupby("category")[ECOREGION_ID]
        .nunique()
        .sort_index()
        .to_dict()
    )
    category_counts = merged[RECOMMENDATION_CATEGORY].fillna("unlabeled_enriched").value_counts().sort_index().to_dict()
    return {
        "species": len(merged),
        "enriched": int(enriched.sum()),
        "unenriched": int((~enriched).sum()),
        "partially_enriched": int((enriched & populated.lt(len(trait_fields))).sum()),
        "category_counts": {str(key): int(value) for key, value in category_counts.items()},
        "trait_completeness": completeness,
        "regional_distribution": {str(key): int(value) for key, value in regional.items()},
    }


def render_markdown(audit: dict) -> str:
    lines = [
        "# Recommendation categorization audit",
        "",
        "_Generated by `python -m etl.recommendation_audit`; the command reads source CSVs and writes only to stdout._",
        "",
        "## Coverage",
        "",
        f"- Unique app species: {audit['species']:,}",
        f"- Enriched under the production predicate: {audit['enriched']:,}",
        f"- Unenriched: {audit['unenriched']:,}",
        f"- Partially enriched: {audit['partially_enriched']:,}",
        "",
        "| Current category | Species | Ecoregions |",
        "|---|---:|---:|",
    ]
    for category, count in audit["category_counts"].items():
        lines.append(f"| `{category}` | {count:,} | {audit['regional_distribution'].get(category, 0):,} |")
    lines.extend(["", "## Enriched trait completeness", "", "| Field | Populated enriched species |", "|---|---:|"])
    for field, count in audit["trait_completeness"].items():
        lines.append(f"| `{field}` | {count:,} |")
    lines.extend(
        [
            "",
            "## Fitness of existing evidence",
            "",
            "The existing LBJ fields can support preliminary horticultural fit: growth habit, duration, height, light, moisture, water use, soil, and bloom traits. They are useful for candidate ranking and for explaining site-dependent choices, but they do not justify final `good_default` or `conditional` assignments by themselves.",
            "",
            "The dataset lacks explicit, source-attributed evidence for toxicity, invasiveness or aggressive spread, handling risk, and specialist habitat or restoration dependence. Those gaps prevent a defensible automatic safety recommendation.",
            "",
            "## Proposed evidence model and rules",
            "",
            "- Store evidence separately from the category: `usageKey`, evidence type, normalized value, source URL, source organization, jurisdiction, retrieved date, confidence, and reviewer note.",
            "- Assign `good_default` only after negative checks for toxicity, invasiveness, handling risk, and specialist dependence, plus broadly satisfiable garden traits.",
            "- Assign `conditional` when a plant is garden-appropriate but has a material site, maintenance, spread, or handling condition that can be explained to users.",
            "- Assign `specialist_restoration` when reliable evidence indicates narrow habitat, parasitic/host dependence, restoration-only practice, or specialist establishment needs.",
            "- Keep `poor_avoid` for supported garden-safety or ecological-risk exclusions and `invalid_ambiguous` for unresolved identity or record-quality failures.",
            "",
            "## Review and migration workflow",
            "",
            "1. Triage enriched unlabeled species by ecoregion reach and trait completeness; do not infer safety from missing evidence.",
            "2. Collect the four missing evidence classes from authoritative, jurisdiction-aware sources and retain citations.",
            "3. Apply deterministic rules to produce a proposed category plus reasons; require human review for conflicts, low confidence, and all exclusion categories.",
            "4. Sample-review approvals and all category transitions, then version the evidence and decision records.",
            "5. In a later data migration, export reviewed assignments to the curation CSV, regenerate app data, and compare category/region counts against this audit. No assignments or generated data are changed by this proposal.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit recommendation category evidence without modifying data.")
    parser.add_argument("--plant-ecoregions", type=Path, default=DEFAULT_PLANT_ECOREGIONS_PATH)
    parser.add_argument("--lbj-traits", type=Path, action="append", dest="lbj_traits")
    parser.add_argument("--recommendation-categories", type=Path, default=DEFAULT_RECOMMENDATION_CATEGORIES_PATH)
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    audit = build_audit(
        pd.read_csv(args.plant_ecoregions, dtype=str),
        read_lbj_traits(args.lbj_traits or DEFAULT_LBJ_TRAITS_PATHS),
        read_recommendation_categories(args.recommendation_categories),
    )
    print(render_markdown(audit))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
